import { randomUUID } from 'node:crypto';
import type { ProductMediaRepository, ProductMediaStorage, WhatsAppMediaProvider, ClaimedProductMedia } from './ProductMediaRepository';
import { ProductMediaAnalyzer } from './ProductMediaAnalyzer';
import { ProductImageSelector } from './ProductImageSelector';
import type { ProductMediaAsset, ProductMediaCandidateInput, ProductPresentationContext } from './types';
import { AdaptiveWorkerLoop } from '../workers/AdaptiveWorkerLoop';
import type { UsageQuotaService } from '../usage/UsageQuotaService';

const MAX_ATTEMPTS = 3; const BACKOFF = [5_000, 30_000]; const STALE_MS = 5 * 60_000;
export class ProductMediaService {
  private readonly workerId = `media-${randomUUID()}`; private draining = false;
  private readonly pendingBytes = new Map<string, { bytes: Uint8Array; mimeType: string | null }>();
  constructor(private readonly repository: ProductMediaRepository, private readonly storage: ProductMediaStorage, private readonly analyzer: ProductMediaAnalyzer, private readonly selector = new ProductImageSelector(), private readonly whatsApp?: WhatsAppMediaProvider, private readonly quota?:UsageQuotaService) {}
  async addCandidate(input: ProductMediaCandidateInput): Promise<ProductMediaAsset> { await this.safeEvent(input.userId, 'product.media.discovery.started', { product_id: input.productId, source_type: input.sourceType }); const asset = await this.repository.createCandidate(input); if (input.bytes) this.pendingBytes.set(asset.id, { bytes: input.bytes, mimeType: input.suppliedMimeType ?? null }); this.kick(); return asset; }
  async addMarketplaceImages(userId: string, productId: string, dealId: string, imageUrls: Array<string | null | undefined>): Promise<void> { const unique=[...new Set(imageUrls.filter((url):url is string=>Boolean(url)))];if(!unique.length){await this.repository.markUnavailable(userId,productId);return;}for(const imageUrl of unique)await this.addCandidate({userId,productId,sourceType:'marketplace',sourceReferenceId:dealId,sourceUrl:imageUrl}); }
  async markUnavailable(userId: string, productId: string): Promise<void> { await this.repository.markUnavailable(userId, productId); }
  async uploadManual(userId: string, productId: string, bytes: Uint8Array, mimeType?: string | null): Promise<ProductMediaAsset> { if (!await this.repository.getOwnedProduct(userId, productId)) throw new Error('PRODUCT_NOT_FOUND'); return this.addCandidate({ userId, productId, sourceType: 'manual', bytes, suppliedMimeType: mimeType }); }
  async list(userId: string, productId: string): Promise<ProductPresentationContext | null> { const product = await this.repository.getOwnedProduct(userId, productId); if (!product) return null; const assets = await this.withSignedUrls(await this.repository.listAssets(userId, productId)); return { productId, primaryImage: assets.find((asset) => asset.isPrimary) ?? null, alternativeImages: assets.filter((asset) => !asset.isPrimary), mediaStatus: product.mediaStatus }; }
  async selectManual(userId: string, productId: string, assetId: string): Promise<boolean> { const selected = await this.repository.selectPrimary(userId, productId, assetId, 'manual_selected'); if (selected) await this.safeEvent(userId, 'product.media.manual_selected', { product_id: productId, asset_id: assetId }); return selected; }
  async drain(maxItems = 30): Promise<number> { if (this.draining) return 0; this.draining = true; let count = 0; try { await this.discoverWhatsApp(); while (count < maxItems) { const claim = await this.repository.claimNext(this.workerId, new Date(Date.now() - STALE_MS).toISOString()); if (!claim) break; await this.process(claim); count++; } return count; } finally { this.draining = false; } }
  kick(): void { void this.drain().catch((error) => console.error('[AfiliHub:Media] Worker falhou.', error)); }
  private async discoverWhatsApp(): Promise<void> { if (!this.whatsApp) return; for (const input of await this.repository.discoverPendingWhatsApp()) { try { const media = await this.whatsApp.download(input); if (!media) { await this.repository.markUnavailable(input.userId, input.productId); continue; } if (!('bytes' in media)) continue; await this.addCandidate({ ...input, bytes: media.bytes, suppliedMimeType: media.mimeType }); } catch { await this.safeEvent(input.userId, 'product.media.failed', { product_id: input.productId, source_type: 'whatsapp', error_code: 'WHATSAPP_MEDIA_DOWNLOAD_FAILED' }); } } }
  private async process(claim: ClaimedProductMedia): Promise<void> { const started = Date.now(); try { let asset = claim.asset; let bytes: Uint8Array; let mime = asset.mimeType; const pending = this.pendingBytes.get(asset.id); if (pending) { bytes = pending.bytes; mime = pending.mimeType; } else if (asset.storagePath) { const storedFile = await this.storage.read(asset.storagePath); bytes = storedFile.bytes; mime = storedFile.mimeType; } else if (asset.sourceUrl) { const source = await this.storage.fetchTrustedSource(asset.sourceUrl); bytes = source.bytes; mime = source.suppliedMimeType; } else { throw new Error('MEDIA_SOURCE_UNAVAILABLE'); }
      const stored = asset.storagePath && asset.contentHash ? { storagePath: asset.storagePath, contentHash: asset.contentHash, mimeType: asset.mimeType!, fileSize: asset.fileSize!, width: asset.width!, height: asset.height! } : await this.storage.store(claim.asset.userId, claim.asset.productId, claim.asset.id, bytes, mime); const claimedId=claim.asset.id;asset = await this.repository.attachStoredFile(claim, stored);this.pendingBytes.delete(claimedId);if(asset.id!==claimedId){await this.autoSelect(asset.userId,asset.productId);return;}
      const analysisSource = stored.analysisBytes ? { bytes:stored.analysisBytes, mimeType:stored.mimeType } : { bytes, mimeType:mime ?? stored.mimeType };
      await this.quota?.consume(asset.userId,'ai_generation');
      const result = await this.analyzer.analyze({ ...analysisSource, productTitle: claim.product.title, productCategory: claim.product.category }); const quality = this.analyzer.quality(result.analysis, stored.width, stored.height); const review = this.analyzer.needsReview(result.analysis); await this.repository.completeAnalysis(claim, result.analysis, quality, review);
      await this.safeEvent(asset.userId, 'product.media.analysis.completed', { product_id: asset.productId, asset_id: asset.id, source_type: asset.sourceType, classification: result.analysis.classification, processing_ms: Date.now() - started }); await this.autoSelect(asset.userId, asset.productId);
    } catch (error) { const code = error instanceof Error ? error.message.slice(0, 100) : 'MEDIA_PROCESSING_FAILED'; const retry = claim.asset.attemptCount < MAX_ATTEMPTS; await this.repository.fail(claim, code, retry ? new Date(Date.now() + (BACKOFF[claim.asset.attemptCount - 1] ?? BACKOFF.at(-1)!)).toISOString() : null); await this.safeEvent(claim.asset.userId, 'product.media.failed', { product_id: claim.asset.productId, asset_id: claim.asset.id, source_type: claim.asset.sourceType, error_code: code, processing_ms: Date.now() - started }); } }
  private async autoSelect(userId: string, productId: string): Promise<void> { const assets = await this.repository.listAssets(userId, productId); const picked = this.selector.select(assets, await this.repository.getPreferences(userId)); if (picked && await this.repository.selectPrimary(userId, productId, picked.id, 'auto_selected')) await this.safeEvent(userId, 'product.media.selected', { product_id: productId, asset_id: picked.id, source_type: picked.sourceType }); }
  private async withSignedUrls(assets: ProductMediaAsset[]): Promise<ProductMediaAsset[]> { return Promise.all(assets.map(async (asset) => ({ ...asset, displayUrl: asset.storagePath ? await this.storage.sign(asset.storagePath) : null }))); }
  private async safeEvent(userId: string, eventType: string, payload: Record<string, unknown>) { try { await this.repository.recordEvent(userId, eventType, payload); } catch { /* telemetria nunca quebra mídia */ } }
}
export class ProductMediaWorker { private readonly loop:AdaptiveWorkerLoop;constructor(private readonly service:ProductMediaService,private readonly intervalMs=5_000){this.loop=new AdaptiveWorkerLoop(()=>this.service.drain(),{minDelayMs:intervalMs,maxDelayMs:60_000});}start(){this.loop.start();}stop(){this.loop.stop();} }
