import { describe,expect,it,vi } from 'vitest';import { ProductMediaService } from './ProductMediaService';import { ProductMediaAnalyzer } from './ProductMediaAnalyzer';
const storage={fetchTrustedSource:vi.fn(),store:vi.fn(),read:vi.fn(),sign:vi.fn()};const analyzer=new ProductMediaAnalyzer({analyzeProductMedia:vi.fn()});
describe('ProductMediaService selective WhatsApp',()=>{it('não baixa mídia quando não há promoção elegível',async()=>{const download=vi.fn();const repository={discoverPendingWhatsApp:vi.fn().mockResolvedValue([]),claimNext:vi.fn().mockResolvedValue(null)};const service=new ProductMediaService(repository as any,storage as any,analyzer,undefined,{download});await service.drain();expect(download).not.toHaveBeenCalled();});it('solicita download somente para produto originado de promoção detectada',async()=>{const input={userId:'u',productId:'p',sourceType:'whatsapp',sourceReferenceId:'c',connectionId:'w',externalGroupId:'g',externalMessageId:'m'};const download=vi.fn().mockResolvedValue({bytes:new Uint8Array([1]),mimeType:'image/png'});const repository={discoverPendingWhatsApp:vi.fn().mockResolvedValue([input]),createCandidate:vi.fn().mockResolvedValue({id:'a'}),claimNext:vi.fn().mockResolvedValue(null)};const service=new ProductMediaService(repository as any,storage as any,analyzer,undefined,{download});await service.drain();expect(download).toHaveBeenCalledWith(input);expect(repository.createCandidate).toHaveBeenCalledWith(expect.objectContaining({sourceType:'whatsapp',bytes:expect.any(Uint8Array)}));});it('falha de download fica isolada no pipeline de mídia',async()=>{const input={userId:'u',productId:'p',sourceType:'whatsapp',connectionId:'w',externalGroupId:'g',externalMessageId:'m'};const repository={discoverPendingWhatsApp:vi.fn().mockResolvedValue([input]),recordEvent:vi.fn(),claimNext:vi.fn().mockResolvedValue(null)};const service=new ProductMediaService(repository as any,storage as any,analyzer,undefined,{download:vi.fn().mockRejectedValue(new Error('timeout'))});await expect(service.drain()).resolves.toBe(0);expect(repository.recordEvent).toHaveBeenCalledWith('u','product.media.failed',expect.any(Object));});});

it('mantém mídia pendente quando a referência durável aguarda retry',async()=>{const input={userId:'u',productId:'p',sourceType:'whatsapp',sourceReferenceId:'c',connectionId:'w',externalGroupId:'g',externalMessageId:'m'};const repository={discoverPendingWhatsApp:vi.fn().mockResolvedValue([input]),markUnavailable:vi.fn(),claimNext:vi.fn().mockResolvedValue(null)};const service=new ProductMediaService(repository as any,storage as any,analyzer,undefined,{download:vi.fn().mockResolvedValue({pending:true})});await service.drain();expect(repository.markUnavailable).not.toHaveBeenCalled();});

describe('ProductMediaService retry e upload manual',()=>{it('upload manual pertence ao usuário e entra no mesmo pipeline',async()=>{const repository={getOwnedProduct:vi.fn().mockResolvedValue({id:'p'}),createCandidate:vi.fn().mockResolvedValue({id:'asset-manual'}),discoverPendingWhatsApp:vi.fn().mockResolvedValue([]),claimNext:vi.fn().mockResolvedValue(null),recordEvent:vi.fn()};const service=new ProductMediaService(repository as any,storage as any,analyzer);await service.uploadManual('u','p',new Uint8Array([1,2]),'image/png');expect(repository.getOwnedProduct).toHaveBeenCalledWith('u','p');expect(repository.createCandidate).toHaveBeenCalledWith(expect.objectContaining({userId:'u',productId:'p',sourceType:'manual'}));});it('encerra após a terceira tentativa',async()=>{const mediaAsset={id:'a',userId:'u',productId:'p',sourceType:'marketplace',sourceUrl:'https://cdn.example/x.png',storagePath:null,mimeType:null,contentHash:null,attemptCount:3};const claim={asset:mediaAsset,product:{id:'p',userId:'u',title:'Produto',category:null},workerId:'worker'};const repository={discoverPendingWhatsApp:vi.fn().mockResolvedValue([]),claimNext:vi.fn().mockResolvedValueOnce(claim).mockResolvedValueOnce(null),fail:vi.fn(),recordEvent:vi.fn()};const failingStorage={...storage,fetchTrustedSource:vi.fn().mockRejectedValue(new Error('MEDIA_DOWNLOAD_TIMEOUT'))};const service=new ProductMediaService(repository as any,failingStorage as any,analyzer);await service.drain();expect(repository.fail).toHaveBeenCalledWith(claim,'MEDIA_DOWNLOAD_TIMEOUT',null);});});

it('impede dois drains concorrentes do mesmo worker',async()=>{let release!:()=>void;const gate=new Promise<void>((resolve)=>{release=resolve;});const claimNext=vi.fn(async()=>{await gate;return null;});const repository={discoverPendingWhatsApp:vi.fn().mockResolvedValue([]),claimNext};const service=new ProductMediaService(repository as any,storage as any,analyzer);const first=service.drain();await Promise.resolve();await expect(service.drain()).resolves.toBe(0);release();await first;expect(claimNext).toHaveBeenCalledTimes(1);});
