import type{DispatchRepository}from'./DispatchRepository';
import type{CreateCampaignInput,QueueSettings}from'./types';
import{validateQueueSettings}from'./QueueScheduleCalculator';

function normalized(input:CreateCampaignInput){const name=input.name?.trim();if(!name||name.length>100)throw new Error('CAMPAIGN_NAME_INVALID');const groupIds=[...new Set(input.groupIds??[])];if(!input.connectionId||!groupIds.length)throw new Error('CAMPAIGN_DESTINATIONS_REQUIRED');const seconds=input.intervalBetweenItemsSeconds??input.defaultIntervalSeconds??30;const settings=validateQueueSettings({mode:input.mode??'continuous',intervalBetweenItemsSeconds:seconds,timezone:input.timezone??'America/Sao_Paulo',allowedStartTime:input.allowedStartTime??'00:00',allowedEndTime:input.allowedEndTime??'23:59',allowedDays:input.allowedDays??[1,2,3,4,5,6,7],fixedSlots:input.fixedSlots??[]} satisfies QueueSettings);return{...input,...settings,name,groupIds,defaultIntervalSeconds:settings.intervalBetweenItemsSeconds};}

export class CampaignService{
  constructor(private repository:DispatchRepository){}
  list(userId:string){return this.repository.listCampaigns(userId);}
  get(userId:string,id:string){return this.repository.getCampaign(userId,id);}
  private async validateDestinations(userId:string,connectionId:string,groupIds:string[]){const connection=await this.repository.getConnection(userId,connectionId);if(!connection)throw new Error('CAMPAIGN_CONNECTION_FORBIDDEN');const groups=await this.repository.getGroups(userId,connectionId,groupIds);if(groups.length!==new Set(groupIds).size)throw new Error('CAMPAIGN_GROUP_FORBIDDEN');if(groups.some(group=>group.connectionId!==connectionId||group.syncStatus!=='active'))throw new Error('CAMPAIGN_GROUP_UNAVAILABLE');}
  async create(userId:string,input:CreateCampaignInput){const value=normalized(input);await this.validateDestinations(userId,value.connectionId,value.groupIds);const campaign=await this.repository.createCampaign(userId,value);await this.repository.recordEvent(userId,'campaign.created',{campaign_id:campaign.id,connection_id:campaign.connectionId,groups:campaign.groups.length});return campaign;}
  async update(userId:string,id:string,input:Partial<CreateCampaignInput>){const current=await this.repository.getCampaign(userId,id);if(!current)throw new Error('CAMPAIGN_NOT_FOUND');if(['cancelled','archived'].includes(current.status))throw new Error('CAMPAIGN_NOT_EDITABLE');const merged=normalized({name:input.name??current.name,connectionId:input.connectionId??current.connectionId,groupIds:input.groupIds??current.groups.map(group=>group.whatsappGroupId),intervalBetweenItemsSeconds:input.intervalBetweenItemsSeconds??input.defaultIntervalSeconds??current.intervalBetweenItemsSeconds,timezone:input.timezone??current.timezone,mode:input.mode??current.mode,allowedStartTime:input.allowedStartTime??current.allowedStartTime,allowedEndTime:input.allowedEndTime??current.allowedEndTime,allowedDays:input.allowedDays??current.allowedDays,fixedSlots:input.fixedSlots??current.fixedSlots});await this.validateDestinations(userId,merged.connectionId,merged.groupIds);return this.repository.updateCampaign(userId,id,merged);}
  async pause(userId:string,id:string){const value=await this.repository.setCampaignStatus(userId,id,'paused');if(!value)throw new Error('CAMPAIGN_NOT_FOUND');await this.repository.recordEvent(userId,'campaign.paused',{campaign_id:id});return value;}
  async resume(userId:string,id:string){const current=await this.repository.getCampaign(userId,id);if(!current)throw new Error('CAMPAIGN_NOT_FOUND');if(current.status!=='paused'&&current.status!=='draft')throw new Error('CAMPAIGN_NOT_RESUMABLE');const value=await this.repository.setCampaignStatus(userId,id,'active');await this.repository.recordEvent(userId,'campaign.resumed',{campaign_id:id});return value;}
  async cancel(userId:string,id:string){const value=await this.repository.cancelCampaign(userId,id);if(!value)throw new Error('CAMPAIGN_NOT_FOUND');await this.repository.recordEvent(userId,'campaign.cancelled',{campaign_id:id});return value;}
  async archive(userId:string,id:string){const value=await this.repository.setCampaignStatus(userId,id,'archived');if(!value)throw new Error('CAMPAIGN_NOT_FOUND');await this.repository.recordEvent(userId,'queue.archived',{queue_id:id});return value;}
}
