import type{CtaBlueprint,CtaExample,CtaFacts,CtaGeneratedSlot,CtaMemoryItem,CtaProductCreativeContext,CtaProfile,CtaRule,CtaStructuredGenerationOutput,CtaStructureOperation,CtaTemplateCreativeContext,CtaTrainingReview}from'./types';
export interface CtaRelevantMemory{rules:CtaRule[];examples:CtaExample[];semanticItems?:CtaMemoryItem[];recentSignatures:string[];recentVariantSlots:CtaGeneratedSlot[][];preferences:string|null;recentCtas?:Array<{text:string;angle:string|null}>;}
export interface CtaCreativeGenerationInput{facts:CtaFacts;creativeContext:CtaProductCreativeContext;templateContext:CtaTemplateCreativeContext;profile:CtaProfile;blueprint:CtaBlueprint;memory:CtaRelevantMemory;instruction:string|null;variantIndex:number;anglePlan?:{objective:string;avoid:string[];diversityDirection:string};candidateCount?:number;}
export interface CtaLearnedExample{text:string;sentiment:'positive'|'negative'|'reference';traits:string[];}
export interface CtaInterpretation{scope:'persistent'|'conditional'|'exception'|'one_off';profilePatch:Record<string,unknown>;ruleChanges:Array<{action:'add'|'archive';ruleType:string;value:string;scope?:'persistent'|'conditional'|'exception'|'one_off';condition?:unknown[]}>;structureOperations:CtaStructureOperation[];example?:CtaLearnedExample;examples?:CtaLearnedExample[];archiveMemoryIds?:string[];feedback?:{strength:string;aspects:Record<string,string>;generationId?:string};requiresConfirmation:boolean;reply:string;changeSummary:string[];}
export interface CtaAIProvider{
  generateCta(input:CtaCreativeGenerationInput):Promise<{output:CtaStructuredGenerationOutput;provider:string;model:string;processingMs:number}>;
  repairCta(input:CtaCreativeGenerationInput&{invalidText:string;invalidSlots:CtaGeneratedSlot[];errors:string[]}):Promise<{output:CtaStructuredGenerationOutput;provider:string;model:string;processingMs:number}>;
  interpretCtaInstruction(input:{message:string;profile:CtaProfile;blueprint:CtaBlueprint;rules:CtaRule[];memory?:CtaMemoryItem[];conversation?:Array<{role:string;content:string}>;recentGenerations:Array<{id:string;text:string;variantIndex:number}>}):Promise<{output:CtaInterpretation;provider:string;model:string;processingMs:number}>;
  interpretTrainingChunk?(input:{content:string;chunkIndex:number;chunkCount:number}):Promise<{output:Omit<CtaTrainingReview,'source'|'counts'|'conflicts'>;provider:string;model:string;processingMs:number}>;
  reconcileTraining?(input:{chunks:Array<Omit<CtaTrainingReview,'source'|'counts'|'conflicts'>>;existing:CtaMemoryItem[]}):Promise<{output:{summary:string[];items:CtaTrainingReview['items'];conflicts:CtaTrainingReview['conflicts']};provider:string;model:string;processingMs:number}>;
}
