import{describe,expect,it,vi}from'vitest';import{CtaGenerationService}from'./CtaGenerationService';import{availableCtaBlocks}from'./defaultBlueprint';import type{CtaBlock,CtaFacts,CtaTemplate}from'./types';
const facts:CtaFacts={productId:'p',title:'Echo Dot',category:null,price:249,originalPrice:399,discountPercent:38,couponCode:'ECHO20',couponDescription:null,freeShipping:true,marketplace:'shopee',affiliateUrl:'https://affiliate.test/a',sourceUrl:'https://source.test'};
const profile={id:'profile',userId:'u',tone:'natural',length:'medium',emojiLevel:'moderate',repetitionMode:'balanced',structuredPreferences:{},naturalLanguagePreferences:null,version:1,createdAt:'',updatedAt:''}as const;
const block=(key:string,position:number)=>({...availableCtaBlocks().find(item=>item.key===key)!,position,frequency:'always' as const});
function setup(blocks:CtaBlock[]){const template:CtaTemplate={id:'t',userId:'u',name:'T',description:null,active:true,isDefault:true,version:1,blocks,presentation:{defaultCaption:'',watermark:{enabled:false,text:'',position:'bottom-right',opacity:0.72}},officialKey:null,createdAt:'',updatedAt:''};const repository={getOrCreateProfile:vi.fn().mockResolvedValue(profile),listRules:vi.fn().mockResolvedValue([]),listRelevantExamples:vi.fn().mockResolvedValue([]),listRecentGenerations:vi.fn().mockResolvedValue([]),getTemplate:vi.fn().mockResolvedValue(template),getDefaultTemplate:vi.fn().mockResolvedValue(template),createGeneration:vi.fn()};const provider={generateCta:vi.fn().mockResolvedValue({output:{slots:[]},provider:'test',model:'test',processingMs:1}),repairCta:vi.fn()};return{service:new CtaGenerationService(repository as any,provider as any),provider};}
describe('block-driven generation',()=>{
  it('template vazio produz string vazia sem chamar IA',async()=>{const{service,provider}=setup([]);const preview=await service.preview('u','t',facts);expect(preview.text).toBe('');expect(provider.generateCta).not.toHaveBeenCalled();expect(provider.repairCta).not.toHaveBeenCalled();});
  it.each([[['price'],'R$ 249,00'],[['product'],'Echo Dot'],[['affiliate_link'],'https://affiliate.test/a']]as const)('template factual %o renderiza somente membership configurado',async(keys,expected)=>{const{service,provider}=setup(keys.map((key,index)=>block(key,index)));const preview=await service.preview('u','t',facts);expect(preview.text).toBe(expected);expect(provider.generateCta).not.toHaveBeenCalled();});
  it('template factual não completa produto, cupom, abertura ou CTA',async()=>{const{service}=setup([block('price',0)]);const text=(await service.preview('u','t',facts)).text;expect(text).not.toMatch(/Echo|ECHO20|oportunidade|confira|https?:/iu);});
  it('Preview usa o draft recebido, não a última versão persistida',async()=>{const{service,provider}=setup([block('opening',0),block('product',1),block('price',2),block('cta',3)]);const preview=await service.preview('u','t',facts,undefined,[block('product',0)]);expect(preview.text).toBe('Echo Dot');expect(provider.generateCta).not.toHaveBeenCalled();});
  it('draft vazio prevalece sobre template persistido preenchido',async()=>{const{service,provider}=setup([block('opening',0),block('product',1),block('price',2)]);const preview=await service.preview('u','t',facts,undefined,[]);expect(preview.text).toBe('');expect(provider.generateCta).not.toHaveBeenCalled();});
  it('IA recebe somente o CTA inicial e o antigo CTA final é ignorado',async()=>{const blocks=[block('opening',0),block('product',1),{...block('opening',2),id:'cta',key:'cta'}];const{service,provider}=setup(blocks);provider.generateCta.mockResolvedValue({output:{slots:[{blockId:'cta_ia',text:'Olha esta novidade'}]},provider:'test',model:'test',processingMs:1});const text=(await service.preview('u','t',facts)).text;expect(provider.generateCta).toHaveBeenCalledOnce();const effective=provider.generateCta.mock.calls[0][0].blueprint.blocks;expect(effective.filter((item:CtaBlock)=>item.copyMode==='AI_GENERATED').map((item:CtaBlock)=>item.id)).toEqual(['cta_ia']);expect(text).toBe('Olha esta novidade\n\nEcho Dot');});
});
