import { Router, type Request, type Response } from 'express';
import { getAuthUser } from '../middleware/auth';
import type { MarketplaceRadarService } from '../../domain/marketplaces/discovery/MarketplaceRadarService';
import type { RadarFilters } from '../../domain/marketplaces/discovery/types';
import type { ConfigurableAffiliatePlatform } from '../../domain/affiliate/types';

async function owner(req: Request,res: Response){const user=await getAuthUser(req);if(!user){res.status(401).json({success:false,error:{code:'UNAUTHORIZED',message:'Usuário não autenticado.'}});return null;}return user.id;}
function send(res:Response,result:any,success=200){if(result.success)return res.status(success).json(result);const code=result.error?.code;return res.status(code==='RADAR_DEAL_NOT_FOUND'?404:code==='FEATURE_NOT_AVAILABLE'?403:code?.startsWith('RADAR_REFRESH_')?409:code==='RADAR_PROVIDER_NOT_CONFIGURED'?503:500).json(result);}
function filters(query:Request['query']):RadarFilters{const number=(v:unknown)=>typeof v==='string'&&v!==''&&Number.isFinite(Number(v))?Number(v):undefined;return{marketplace:typeof query.marketplace==='string'?query.marketplace as any:undefined,category:typeof query.category==='string'?query.category:undefined,minPrice:number(query.minPrice),maxPrice:number(query.maxPrice),minDiscount:number(query.minDiscount),minCommission:number(query.minCommission),freeShipping:query.freeShipping==='true',coupon:query.coupon==='true',sort:typeof query.sort==='string'?query.sort as any:undefined,cursor:typeof query.cursor==='string'?query.cursor:undefined,limit:number(query.limit)};}
function marketplace(value:unknown):ConfigurableAffiliatePlatform{return value==='amazon'||value==='mercado_livre'?value:'shopee';}
export function createMarketplaceRadarRouter(service:MarketplaceRadarService){const router=Router();router.get('/deals',async(req,res)=>{const id=await owner(req,res);if(id)send(res,await service.list(id,filters(req.query)));});router.get('/deals/:id',async(req,res)=>{const id=await owner(req,res);if(id)send(res,await service.get(id,req.params.id));});router.post('/refresh',async(req,res)=>{const id=await owner(req,res);if(id)send(res,await service.refresh(id,marketplace(req.body?.marketplace),'manual'));});router.post('/deals/:id/prepare',async(req,res)=>{const id=await owner(req,res);if(id)send(res,await service.prepare(id,req.params.id),201);});return router;}
