import type{SupabaseClient}from'@supabase/supabase-js';import type{WhatsAppMediaReferenceRecord,WhatsAppMediaReferenceRepository}from'../../domain/whatsapp/mediaReferences';
type Row=Record<string,any>;const map=(row:Row):WhatsAppMediaReferenceRecord=>({id:row.id,userId:row.user_id,connectionId:row.connection_id,capturedMessageId:row.captured_message_id,externalGroupId:row.external_group_id,externalMessageId:row.external_message_id,mediaType:row.media_type,mimeType:row.mime_type??null,encryptedPayload:row.retrieval_payload_encrypted??null,status:row.status,expiresAt:row.expires_at,attemptCount:Number(row.attempt_count??0),workerId:row.processing_worker_id??null});
export class SupabaseWhatsAppMediaReferenceRepository implements WhatsAppMediaReferenceRepository{constructor(private readonly db:SupabaseClient){}
  async upsert(input:Parameters<WhatsAppMediaReferenceRepository['upsert']>[0]){const{data,error}=await this.db.rpc('upsert_whatsapp_media_reference',{p_user_id:input.userId,p_connection_id:input.connectionId,p_captured_message_id:input.capturedMessageId,p_external_group_id:input.externalGroupId,p_external_message_id:input.externalMessageId,p_media_type:input.mediaType,p_mime_type:input.mimeType,p_retrieval_payload_encrypted:input.encryptedPayload,p_expires_at:input.expiresAt});if(error)throw error;return String(data);}
  async claimForCapture(input:Parameters<WhatsAppMediaReferenceRepository['claimForCapture']>[0]){const{data,error}=await this.db.rpc('claim_whatsapp_media_reference',{p_user_id:input.userId,p_captured_message_id:input.capturedMessageId,p_worker_id:input.workerId,p_stale_before:input.staleBefore});if(error)throw error;const row=Array.isArray(data)?data[0]:data;return row?map(row):null;}
  async markDownloaded(reference:WhatsAppMediaReferenceRecord){const{error}=await this.db.from('whatsapp_media_references').update({status:'downloaded',downloaded_at:new Date().toISOString(),retrieval_payload_encrypted:null,processing_started_at:null,processing_worker_id:null,last_error_code:null,updated_at:new Date().toISOString()}).eq('user_id',reference.userId).eq('captured_message_id',reference.capturedMessageId).in('status',['pending','claimed']);if(error)throw error;}
  async markFailure(reference:WhatsAppMediaReferenceRecord,input:Parameters<WhatsAppMediaReferenceRepository['markFailure']>[1]){const terminal=input.status!=='pending';const{error}=await this.db.from('whatsapp_media_references').update({status:input.status,next_attempt_at:input.retryAt??new Date().toISOString(),retrieval_payload_encrypted:terminal?null:reference.encryptedPayload,processing_started_at:null,processing_worker_id:null,last_error_code:input.errorCode,last_attempt_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',reference.id).eq('user_id',reference.userId).eq('processing_worker_id',reference.workerId);if(error)throw error;}
  async cleanup(){const{data,error}=await this.db.rpc('cleanup_whatsapp_media_references');if(error)throw error;return Number(data??0);}
  async hasPending(userId:string,capturedMessageId:string){const{count,error}=await this.db.from('whatsapp_media_references').select('id',{count:'exact',head:true}).eq('user_id',userId).eq('captured_message_id',capturedMessageId).in('status',['pending','claimed']).gt('expires_at',new Date().toISOString());if(error)throw error;return(count??0)>0;}
}
