import{randomUUID}from'node:crypto';import type{IncomingWhatsAppMessage}from'../../domain/monitoring/types';import type{WhatsAppMediaProvider}from'../../domain/media/ProductMediaRepository';import type{NormalizedMediaReference,WhatsAppMediaReferenceRepository,WhatsAppReferenceDownloader}from'../../domain/whatsapp/mediaReferences';import{decryptProtectedPayload,encryptProtectedPayload}from'./sessionCrypto';
const STALE_MS=5*60_000;const BACKOFF=[5_000,30_000];
function validate(value:unknown):NormalizedMediaReference{const row=value as Record<string,unknown>;const key=typeof row?.mediaKeyBase64==='string'?Buffer.from(row.mediaKeyBase64,'base64'):Buffer.alloc(0);const direct=typeof row?.directPath==='string'&&row.directPath.startsWith('/')?row.directPath:null;const url=typeof row?.url==='string'&&row.url.startsWith('https://mmg.whatsapp.net/')?row.url:null;if(row?.mediaType!=='image'||key.length!==32||(!direct&&!url))throw new Error('WHATSAPP_MEDIA_INVALID_REFERENCE');return{mediaType:'image',mediaKeyBase64:key.toString('base64'),directPath:direct,url:direct?null:url};}
export class WhatsAppMediaReferenceService implements WhatsAppMediaProvider{private readonly workerId=`whatsapp-media-${randomUUID()}`;constructor(private readonly repository:WhatsAppMediaReferenceRepository,private readonly downloader:WhatsAppReferenceDownloader,private readonly ttlMs=7*24*60*60_000){}
  async register(userId:string,capturedMessageId:string,message:IncomingWhatsAppMessage):Promise<string|null>{const reference=message.mediaRecoveryReference;if(!reference||message.type!=='image'||message.fromMe||!message.externalGroupId.endsWith('@g.us'))return null;const safe=validate(reference);return this.repository.upsert({userId,connectionId:message.connectionId,capturedMessageId,externalGroupId:message.externalGroupId,externalMessageId:message.externalMessageId,mediaType:'image',mimeType:message.media?.mimeType??null,encryptedPayload:encryptProtectedPayload(JSON.stringify(safe)),expiresAt:new Date(Date.now()+this.ttlMs).toISOString()});}
  async download(input:{userId?:string;sourceReferenceId?:string|null;connectionId:string;externalGroupId:string;externalMessageId:string}){if(!input.userId||!input.sourceReferenceId)return null;for(let source=0;source<5;source++){const reference=await this.repository.claimForCapture({userId:input.userId,capturedMessageId:input.sourceReferenceId,workerId:this.workerId,staleBefore:new Date(Date.now()-STALE_MS).toISOString()});if(!reference)break;if(new Date(reference.expiresAt).getTime()<=Date.now()){await this.repository.markFailure(reference,{status:'expired',errorCode:'WHATSAPP_MEDIA_REFERENCE_EXPIRED'});continue;}let payload:NormalizedMediaReference;try{payload=validate(JSON.parse(decryptProtectedPayload(reference.encryptedPayload??'')));}catch{await this.repository.markFailure(reference,{status:'unavailable',errorCode:'WHATSAPP_MEDIA_INVALID_REFERENCE'});continue;}const result=await this.downloader.downloadReference({connectionId:reference.connectionId,externalGroupId:reference.externalGroupId,externalMessageId:reference.externalMessageId,reference:payload});if(result.success===true){await this.repository.markDownloaded(reference);return{bytes:result.bytes,mimeType:reference.mimeType??result.mimeType};}if(result.transient&&reference.attemptCount<3){const delay=BACKOFF[Math.min(reference.attemptCount-1,BACKOFF.length-1)];await this.repository.markFailure(reference,{status:'pending',errorCode:result.errorCode,retryAt:new Date(Date.now()+delay).toISOString()});continue;}await this.repository.markFailure(reference,{status:result.errorCode.includes('UNAVAILABLE')?'unavailable':'failed',errorCode:result.errorCode});}return await this.repository.hasPending(input.userId,input.sourceReferenceId)?{pending:true as const}:null;}
  cleanup(){return this.repository.cleanup();}
}
export class WhatsAppMediaReferenceMaintenance{private timer:NodeJS.Timeout|null=null;constructor(private readonly service:WhatsAppMediaReferenceService,private readonly intervalMs=60*60_000){}start(){if(this.timer)return;void this.service.cleanup().catch(()=>undefined);this.timer=setInterval(()=>void this.service.cleanup().catch(()=>undefined),this.intervalMs);this.timer.unref?.();}stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}}
