import assert from 'node:assert/strict';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createServer } from 'vite';
import { chromium } from 'playwright-core';

// Monta o componente real com APIs controladas; nenhum dado real é alterado.
const fixture = `<!doctype html><html lang="pt-BR"><head><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><div id="root" style="max-width:1200px;margin:auto;padding:16px"></div><script type="module">
import React from 'react';
import { createRoot } from 'react-dom/client';
import { CtaStudioView } from '/src/views/CtaStudioView.tsx';
import { ctaApi } from '/src/services/ctaApi.ts';
import { productsApi } from '/src/services/productsApi.ts';
import '/src/index.css';
const profile = { id:'p', version:1, naturalLanguagePreferences:'Use linguagem natural' };
const memory = {version:1,general:[],conditional:[],exceptions:[],avoid:[],examples:[]};
const state = window.audit = {calls:{},fail:new URL(location.href).searchParams.get('fail'),delay:0,conversation:[],examples:[],memory,failRefresh:false};
const invoke = async (name, value) => { state.calls[name]=(state.calls[name]||0)+1; if(state.delay) await new Promise(r=>setTimeout(r,state.delay)); if(state.fail===name) throw Error('Falha simulada: '+name); return typeof value==='function' ? value() : value; };
ctaApi.profile = () => invoke('profile', () => { if(state.failRefresh) throw Error('refresh indisponível'); return profile; });
ctaApi.conversation = () => invoke('conversation', state.conversation);
ctaApi.learnedMemory = () => invoke('memory', state.memory);
ctaApi.examples = () => invoke('examples', state.examples);
productsApi.list = () => invoke('products', [{id:'p1',title:'Echo Dot'},{id:'p2',title:'Air Fryer'}]);
ctaApi.assistant = text => invoke('assistant', () => {state.conversation=[...state.conversation,{id:'u'+Date.now(),role:'user',content:text,metadata:{}},{id:'a'+Date.now(),role:'assistant',content:'Preferência registrada',metadata:{}}];return {profile,reply:'Preferência registrada',requiresConfirmation:false};});
ctaApi.analyzeTraining = source => invoke('analyze', {source:{id:'source',charCount:source.length,chunkCount:1},summary:['Prefere CTA natural'],items:[{}],counts:{rules:1,conditions:0,avoided:0,positiveExamples:0,negativeExamples:0},conflicts:[]});
ctaApi.applyTraining = () => invoke('apply', () => { if(state.failRefreshAfterApply) state.failRefresh=true; return {items:1,memoryVersion:2}; });
ctaApi.testCta = (id,{count}) => invoke('test', Array.from({length:count},(_,i)=>({text:(id==='p1'?'Echo Dot':'Air Fryer')+': uma descoberta para a rotina '+i,angle:'ângulo '+i})));
ctaApi.addExample = value => invoke('rate',()=>state.examples=[...state.examples,{id:'example',...value,createdAt:''}]);
ctaApi.deleteExample = id => invoke('removeExample',()=>state.examples=state.examples.filter(x=>x.id!==id));
ctaApi.deleteMemoryItem = () => invoke('removeMemory',true);
ctaApi.resetMemory = () => invoke('reset',()=>{state.conversation=[];state.examples=[];state.memory={...memory,version:0};});
createRoot(document.getElementById('root')).render(React.createElement(CtaStudioView));
</script></body></html>`;

const server = await createServer({ server: { host: '127.0.0.1', port: 0, hmr: false }, plugins: [{ name: 'trainer-audit-page', configureServer(s) { s.middlewares.use('/__trainer_audit', async (_req,res,next) => { try {res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml('/__trainer_audit',fixture));} catch(e) {next(e);} }); } }] });
let browser;
const results = [];
const outputDir = path.resolve('.runtime/cta-audit'); mkdirSync(outputDir,{recursive:true});
try {
  await server.listen();
  const executablePath = process.env.CTA_TEST_BROWSER || [
    'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
    'C:/Program Files/Google/Chrome/Application/chrome.exe', '/usr/bin/chromium', '/usr/bin/google-chrome',
  ].find(existsSync);
  browser = await chromium.launch({ headless:true, ...(executablePath ? {executablePath} : {}) });
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = []; page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.message);});
  page.on('console',message=>{if(message.type()==='error') console.error('Console:',message.text());});
  await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1' ? route.continue() : route.abort());
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/__trainer_audit`);
  await page.getByRole('heading',{name:'Treinador de IA',exact:true}).waitFor();
  await page.getByText('Use linguagem natural',{exact:true}).waitFor();
  results.push('carregamento do perfil e da memória');
  const draft=page.getByRole('textbox',{name:'Mensagem para o treinador'});
  await draft.fill('Sempre escreva naturalmente');
  await page.evaluate(()=>window.audit.fail='assistant');
  await page.getByRole('button',{name:'Enviar',exact:true}).click();
  await page.getByText('Falha simulada: assistant',{exact:true}).waitFor();
  assert.equal(await draft.inputValue(),'Sempre escreva naturalmente');
  results.push('falha no envio preserva o rascunho');
  await page.evaluate(()=>{window.audit.fail=null;window.audit.delay=50;});
  await page.getByRole('button',{name:'Enviar',exact:true}).evaluate(button=>{button.click();button.click();});
  await page.getByText('Preferência registrada',{exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('textarea[aria-label="Mensagem para o treinador"]').value==='');
  assert.equal(await page.evaluate(()=>window.audit.calls.assistant),2);
  results.push('reenvio e proteção contra clique duplo');
  await page.getByRole('button',{name:'Gerar 3 ângulos',exact:true}).click();
  await page.getByRole('button',{name:'Opção 3',exact:true}).click();
  await page.getByRole('button',{name:'Gostei',exact:true}).click();
  const feedback=page.getByRole('heading',{name:'Feedback dos CTAs'}).locator('..');
  await feedback.getByText('Echo Dot: uma descoberta para a rotina 2',{exact:true}).waitFor();
  results.push('geração de três opções, seleção e feedback visível');
  await feedback.getByRole('button',{name:'Remover memória'}).click();
  await feedback.getByText('Nada registrado.',{exact:true}).waitFor();
  await page.getByRole('combobox').selectOption('p2');
  assert.equal(await page.getByRole('button',{name:'Gostei',exact:true}).count(),0);
  results.push('remoção de feedback e troca de produto limpa CTA anterior');
  const source=page.getByRole('textbox',{name:'Fonte do treinamento'});
  await source.fill('Use CTAs naturais sem urgência falsa');
  await page.getByRole('button',{name:'Analisar treinamento',exact:true}).click();
  await page.getByText('Prefere CTA natural',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Corrigir fonte',exact:true}).click();
  assert.equal(await source.inputValue(),'Use CTAs naturais sem urgência falsa');
  await page.getByRole('button',{name:'Analisar treinamento',exact:true}).click();
  await page.getByRole('button',{name:'Aplicar',exact:true}).waitFor();
  await page.evaluate(()=>window.audit.failRefreshAfterApply=true);
  await page.getByRole('button',{name:'Aplicar',exact:true}).click();
  await page.getByText('Treinamento aplicado. Reabra a tela para atualizar a memória.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Aplicar',exact:true}).count(),0);
  results.push('revisão, correção da fonte e aplicação sem repetição após falha de refresh');
  await page.evaluate(()=>window.audit.failRefresh=false);
  await page.getByRole('button',{name:'Excluir memória',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.audit.calls.reset||0),0);
  await page.getByRole('button',{name:'Excluir memória',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Excluir memória e começar do zero'}).click();
  await page.getByText('Memória do Treinador apagada.',{exact:false}).waitFor();
  results.push('cancelamento e confirmação do reset com dados fictícios');
  await page.screenshot({path:path.join(outputDir,'trainer-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(outputDir,'trainer-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  results.push('layout móvel sem rolagem horizontal');
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/__trainer_audit?fail=products`);
  await page.getByText('Use linguagem natural',{exact:true}).waitFor();
  await page.getByText('Não foi possível carregar os produtos.',{exact:false}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Gerar CTA de teste',exact:true}).isDisabled(),true);
  results.push('falha nos produtos mantém conversa e memória acessíveis');
  assert.deepEqual(errors,[]);
  results.push('nenhum erro JavaScript no navegador');
  writeFileSync(path.join(outputDir,'ui-results.json'),JSON.stringify({passed:results.length,results},null,2));
  console.log(JSON.stringify({passed:results.length,results},null,2));
} finally { await browser?.close(); await server.close(); }
