-- AfiliHub 3E — CTA Intelligence + Structure Studio. Incremental; não altera migrations aplicadas.
ALTER TABLE public.cta_profiles ADD COLUMN IF NOT EXISTS structured_preferences JSONB NOT NULL DEFAULT '{}'::jsonb,ADD COLUMN IF NOT EXISTS natural_language_preferences TEXT,ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1 CHECK(version>0);
ALTER TABLE public.cta_rules DROP CONSTRAINT IF EXISTS cta_rules_rule_type_check;
ALTER TABLE public.cta_rules ADD COLUMN IF NOT EXISTS scope TEXT NOT NULL DEFAULT 'persistent' CHECK(scope IN('persistent','conditional','one_off')),ADD COLUMN IF NOT EXISTS condition JSONB NOT NULL DEFAULT '[]'::jsonb,ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE,ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,ADD COLUMN IF NOT EXISTS supersedes_rule_id UUID REFERENCES public.cta_rules(id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.cta_history ADD COLUMN IF NOT EXISTS product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,ADD COLUMN IF NOT EXISTS cta_profile_id UUID REFERENCES public.cta_profiles(id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS generated_text TEXT,ADD COLUMN IF NOT EXISTS final_text TEXT,ADD COLUMN IF NOT EXISTS was_edited BOOLEAN NOT NULL DEFAULT FALSE,ADD COLUMN IF NOT EXISTS generation_mode TEXT NOT NULL DEFAULT 'single',ADD COLUMN IF NOT EXISTS publishable BOOLEAN NOT NULL DEFAULT FALSE,ADD COLUMN IF NOT EXISTS generation_status TEXT NOT NULL DEFAULT 'draft' CHECK(generation_status IN('draft','generating','generated','validating','valid','invalid','generation_failed')),ADD COLUMN IF NOT EXISTS structure_signature TEXT,ADD COLUMN IF NOT EXISTS structure_snapshot JSONB,ADD COLUMN IF NOT EXISTS provider TEXT,ADD COLUMN IF NOT EXISTS model TEXT,ADD COLUMN IF NOT EXISTS validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,ADD COLUMN IF NOT EXISTS variant_index INTEGER NOT NULL DEFAULT 0 CHECK(variant_index BETWEEN 0 AND 2),ADD COLUMN IF NOT EXISTS variant_group_id UUID,ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
UPDATE public.cta_history SET generated_text=COALESCE(generated_text,cta_text),final_text=COALESCE(final_text,cta_text) WHERE generated_text IS NULL OR final_text IS NULL;
ALTER TABLE public.cta_history ALTER COLUMN generated_text SET NOT NULL,ALTER COLUMN final_text SET NOT NULL;
ALTER TABLE public.cta_conversations ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,ADD COLUMN IF NOT EXISTS conversation_key UUID,ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.cta_profile_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,profile_id UUID NOT NULL REFERENCES public.cta_profiles(id) ON DELETE CASCADE,version INTEGER NOT NULL,profile_snapshot JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(profile_id,version));
CREATE TABLE IF NOT EXISTS public.cta_blueprints(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,profile_id UUID NOT NULL REFERENCES public.cta_profiles(id) ON DELETE CASCADE,is_default BOOLEAN NOT NULL DEFAULT TRUE,version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),blocks JSONB NOT NULL CHECK(jsonb_typeof(blocks)='array' AND jsonb_array_length(blocks) BETWEEN 1 AND 30),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE UNIQUE INDEX IF NOT EXISTS cta_blueprints_default_uidx ON public.cta_blueprints(user_id) WHERE is_default;
CREATE TABLE IF NOT EXISTS public.cta_blueprint_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,blueprint_id UUID NOT NULL REFERENCES public.cta_blueprints(id) ON DELETE CASCADE,version INTEGER NOT NULL,blocks JSONB NOT NULL,operations JSONB NOT NULL DEFAULT '[]'::jsonb,source TEXT NOT NULL CHECK(source IN('system','manual','assistant','undo')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(blueprint_id,version));
CREATE TABLE IF NOT EXISTS public.cta_examples(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,original_text TEXT NOT NULL CHECK(length(original_text) BETWEEN 1 AND 20000),sentiment TEXT NOT NULL CHECK(sentiment IN('positive','negative','reference')),inferred_traits JSONB NOT NULL DEFAULT '[]'::jsonb,context JSONB NOT NULL DEFAULT '{}'::jsonb,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.cta_feedback(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,generation_id UUID REFERENCES public.cta_history(id) ON DELETE CASCADE,strength TEXT NOT NULL CHECK(strength IN('weak_positive','positive','strong_positive','weak_negative','negative','strong_negative')),aspects JSONB NOT NULL DEFAULT '{}'::jsonb,feedback_text TEXT NOT NULL,explicit BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.cta_inferred_preferences(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,inference_type TEXT NOT NULL,inferred_value JSONB NOT NULL,evidence_count INTEGER NOT NULL DEFAULT 1 CHECK(evidence_count>0),status TEXT NOT NULL DEFAULT 'suggested' CHECK(status IN('suggested','accepted','dismissed')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),resolved_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS cta_history_user_created_idx ON public.cta_history(user_id,created_at DESC);CREATE INDEX IF NOT EXISTS cta_history_product_idx ON public.cta_history(user_id,product_id,created_at DESC);CREATE INDEX IF NOT EXISTS cta_examples_retrieval_idx ON public.cta_examples(user_id,active,created_at DESC);CREATE INDEX IF NOT EXISTS cta_feedback_generation_idx ON public.cta_feedback(user_id,generation_id);CREATE INDEX IF NOT EXISTS cta_inferences_status_idx ON public.cta_inferred_preferences(user_id,status,created_at DESC);CREATE INDEX IF NOT EXISTS cta_conversations_user_created_idx ON public.cta_conversations(user_id,created_at DESC);

ALTER TABLE public.cta_profile_versions ENABLE ROW LEVEL SECURITY;ALTER TABLE public.cta_blueprints ENABLE ROW LEVEL SECURITY;ALTER TABLE public.cta_blueprint_versions ENABLE ROW LEVEL SECURITY;ALTER TABLE public.cta_examples ENABLE ROW LEVEL SECURITY;ALTER TABLE public.cta_feedback ENABLE ROW LEVEL SECURITY;ALTER TABLE public.cta_inferred_preferences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cta_profile_versions_owner ON public.cta_profile_versions;CREATE POLICY cta_profile_versions_owner ON public.cta_profile_versions FOR ALL USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
DROP POLICY IF EXISTS cta_blueprints_owner ON public.cta_blueprints;CREATE POLICY cta_blueprints_owner ON public.cta_blueprints FOR ALL USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
DROP POLICY IF EXISTS cta_blueprint_versions_owner ON public.cta_blueprint_versions;CREATE POLICY cta_blueprint_versions_owner ON public.cta_blueprint_versions FOR ALL USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
DROP POLICY IF EXISTS cta_examples_owner ON public.cta_examples;CREATE POLICY cta_examples_owner ON public.cta_examples FOR ALL USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
DROP POLICY IF EXISTS cta_feedback_owner ON public.cta_feedback;CREATE POLICY cta_feedback_owner ON public.cta_feedback FOR ALL USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
DROP POLICY IF EXISTS cta_inferred_preferences_owner ON public.cta_inferred_preferences;CREATE POLICY cta_inferred_preferences_owner ON public.cta_inferred_preferences FOR ALL USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());

CREATE OR REPLACE FUNCTION public.validate_cta_ownership()RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$BEGIN IF TG_TABLE_NAME='cta_blueprints' AND NOT EXISTS(SELECT 1 FROM public.cta_profiles p WHERE p.id=NEW.profile_id AND p.user_id=NEW.user_id)THEN RAISE EXCEPTION 'CTA_PROFILE_OWNER_MISMATCH';ELSIF TG_TABLE_NAME='cta_blueprint_versions' AND NOT EXISTS(SELECT 1 FROM public.cta_blueprints b WHERE b.id=NEW.blueprint_id AND b.user_id=NEW.user_id)THEN RAISE EXCEPTION 'CTA_BLUEPRINT_OWNER_MISMATCH';ELSIF TG_TABLE_NAME='cta_feedback' AND NEW.generation_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.cta_history h WHERE h.id=NEW.generation_id AND h.user_id=NEW.user_id)THEN RAISE EXCEPTION 'CTA_GENERATION_OWNER_MISMATCH';ELSIF TG_TABLE_NAME='cta_history' AND(NEW.product_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.products p WHERE p.id=NEW.product_id AND p.user_id=NEW.user_id)OR NEW.cta_profile_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.cta_profiles p WHERE p.id=NEW.cta_profile_id AND p.user_id=NEW.user_id))THEN RAISE EXCEPTION 'CTA_HISTORY_OWNER_MISMATCH';END IF;RETURN NEW;END$$;
DROP TRIGGER IF EXISTS validate_cta_blueprints_owner ON public.cta_blueprints;CREATE TRIGGER validate_cta_blueprints_owner BEFORE INSERT OR UPDATE ON public.cta_blueprints FOR EACH ROW EXECUTE FUNCTION public.validate_cta_ownership();DROP TRIGGER IF EXISTS validate_cta_blueprint_versions_owner ON public.cta_blueprint_versions;CREATE TRIGGER validate_cta_blueprint_versions_owner BEFORE INSERT OR UPDATE ON public.cta_blueprint_versions FOR EACH ROW EXECUTE FUNCTION public.validate_cta_ownership();DROP TRIGGER IF EXISTS validate_cta_feedback_owner ON public.cta_feedback;CREATE TRIGGER validate_cta_feedback_owner BEFORE INSERT OR UPDATE ON public.cta_feedback FOR EACH ROW EXECUTE FUNCTION public.validate_cta_ownership();DROP TRIGGER IF EXISTS validate_cta_history_owner ON public.cta_history;CREATE TRIGGER validate_cta_history_owner BEFORE INSERT OR UPDATE ON public.cta_history FOR EACH ROW EXECUTE FUNCTION public.validate_cta_ownership();

CREATE OR REPLACE FUNCTION public.snapshot_cta_profile()RETURNS TRIGGER LANGUAGE plpgsql SET search_path=public AS $$BEGIN INSERT INTO public.cta_profile_versions(user_id,profile_id,version,profile_snapshot)VALUES(NEW.user_id,NEW.id,NEW.version,jsonb_build_object('tone',NEW.tone,'length',NEW.length,'emojiLevel',NEW.emoji_level,'repetitionMode',NEW.repetition_mode,'structuredPreferences',NEW.structured_preferences,'naturalLanguagePreferences',NEW.natural_language_preferences))ON CONFLICT(profile_id,version)DO NOTHING;RETURN NEW;END$$;DROP TRIGGER IF EXISTS snapshot_cta_profile_trigger ON public.cta_profiles;CREATE TRIGGER snapshot_cta_profile_trigger AFTER INSERT OR UPDATE ON public.cta_profiles FOR EACH ROW EXECUTE FUNCTION public.snapshot_cta_profile();
INSERT INTO public.cta_profile_versions(user_id,profile_id,version,profile_snapshot)SELECT user_id,id,version,jsonb_build_object('tone',tone,'length',length,'emojiLevel',emoji_level,'repetitionMode',repetition_mode,'structuredPreferences',structured_preferences,'naturalLanguagePreferences',natural_language_preferences)FROM public.cta_profiles ON CONFLICT(profile_id,version)DO NOTHING;

CREATE OR REPLACE FUNCTION public.update_cta_profile_versioned(p_user_id UUID,p_patch JSONB)RETURNS SETOF public.cta_profiles LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$BEGIN RETURN QUERY UPDATE public.cta_profiles p SET tone=COALESCE(p_patch->>'tone',p.tone),length=COALESCE(p_patch->>'length',p.length),emoji_level=COALESCE(p_patch->>'emoji_level',p.emoji_level),repetition_mode=COALESCE(p_patch->>'repetition_mode',p.repetition_mode),structured_preferences=COALESCE(p_patch->'structured_preferences',p.structured_preferences),natural_language_preferences=CASE WHEN p_patch?'natural_language_preferences'THEN p_patch->>'natural_language_preferences' ELSE p.natural_language_preferences END,version=p.version+1,updated_at=NOW() WHERE p.user_id=p_user_id RETURNING p.*;END$$;
CREATE OR REPLACE FUNCTION public.save_cta_blueprint_version(p_user_id UUID,p_blueprint_id UUID,p_blocks JSONB,p_operations JSONB,p_source TEXT)RETURNS SETOF public.cta_blueprints LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v_version INTEGER;BEGIN IF jsonb_typeof(p_blocks)<>'array'OR jsonb_array_length(p_blocks)NOT BETWEEN 1 AND 30 THEN RAISE EXCEPTION 'CTA_STRUCTURE_INVALID';END IF;UPDATE public.cta_blueprints SET blocks=p_blocks,version=version+1,updated_at=NOW()WHERE id=p_blueprint_id AND user_id=p_user_id RETURNING version INTO v_version;IF v_version IS NULL THEN RAISE EXCEPTION 'CTA_BLUEPRINT_NOT_FOUND';END IF;INSERT INTO public.cta_blueprint_versions(user_id,blueprint_id,version,blocks,operations,source)VALUES(p_user_id,p_blueprint_id,v_version,p_blocks,COALESCE(p_operations,'[]'::jsonb),p_source);RETURN QUERY SELECT*FROM public.cta_blueprints WHERE id=p_blueprint_id AND user_id=p_user_id;END$$;
CREATE OR REPLACE FUNCTION public.undo_cta_blueprint(p_user_id UUID)RETURNS SETOF public.cta_blueprints LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v_blueprint public.cta_blueprints%ROWTYPE;v_previous JSONB;v_new_version INTEGER;BEGIN SELECT*INTO v_blueprint FROM public.cta_blueprints WHERE user_id=p_user_id AND is_default FOR UPDATE;IF v_blueprint.id IS NULL THEN RETURN;END IF;SELECT blocks INTO v_previous FROM public.cta_blueprint_versions WHERE blueprint_id=v_blueprint.id AND version<v_blueprint.version ORDER BY version DESC LIMIT 1;IF v_previous IS NULL THEN RETURN;END IF;v_new_version:=v_blueprint.version+1;UPDATE public.cta_blueprints SET blocks=v_previous,version=v_new_version,updated_at=NOW()WHERE id=v_blueprint.id;INSERT INTO public.cta_blueprint_versions(user_id,blueprint_id,version,blocks,operations,source)VALUES(p_user_id,v_blueprint.id,v_new_version,v_previous,'[]','undo');RETURN QUERY SELECT*FROM public.cta_blueprints WHERE id=v_blueprint.id;END$$;
REVOKE ALL ON FUNCTION public.update_cta_profile_versioned(UUID,JSONB),public.save_cta_blueprint_version(UUID,UUID,JSONB,JSONB,TEXT),public.undo_cta_blueprint(UUID)FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.update_cta_profile_versioned(UUID,JSONB),public.save_cta_blueprint_version(UUID,UUID,JSONB,JSONB,TEXT),public.undo_cta_blueprint(UUID)TO service_role;
