import type { SupabaseClient } from '@supabase/supabase-js';
import type { ClaimedProductMedia, ProductMediaRepository, StoredImage } from '../../domain/media/ProductMediaRepository';
import type { ProductMediaAnalysis, ProductMediaAsset, ProductMediaCandidateInput, ProductMediaPreferences, ProductMediaStatus } from '../../domain/media/types';

type Row = Record<string, any>;
function mapAsset(row: Row): ProductMediaAsset { return { id:row.id,userId:row.user_id,productId:row.product_id,sourceType:row.source_type,sourceReferenceId:row.source_reference_id??null,sourceUrl:row.source_url??null,storagePath:row.storage_path??null,mimeType:row.mime_type??null,fileSize:row.file_size==null?null:Number(row.file_size),width:row.width??null,height:row.height??null,contentHash:row.content_hash??null,classification:row.classification??null,hasTextOverlay:Boolean(row.has_text_overlay),hasDetectedBranding:Boolean(row.has_detected_branding),hasQrCode:Boolean(row.has_qr_code),hasWatermark:Boolean(row.has_watermark),possibleConflictingCommercialText:Boolean(row.possible_conflicting_commercial_text),productMatchConfidence:row.product_match_confidence==null?null:Number(row.product_match_confidence),qualityScore:row.quality_score==null?null:Number(row.quality_score),analysisStatus:row.analysis_status,selectionStatus:row.selection_status,isPrimary:Boolean(row.is_primary),attemptCount:Number(row.attempt_count??0),displayUrl:null,createdAt:row.created_at,updatedAt:row.updated_at }; }

export class SupabaseProductMediaRepository implements ProductMediaRepository {
  constructor(private readonly db: SupabaseClient) {}
  async getOwnedProduct(userId:string,productId:string){const {data,error}=await this.db.from('products').select('id,title,category,media_status').eq('id',productId).eq('user_id',userId).maybeSingle();if(error)throw error;return data?{id:data.id,title:data.title,category:data.category??null,mediaStatus:(data.media_status??'pending') as ProductMediaStatus}:null;}
  async createCandidate(input:ProductMediaCandidateInput):Promise<ProductMediaAsset>{
    if (input.sourceUrl) { const {data:existing,error:findError}=await this.db.from('product_media_assets').select('*').eq('user_id',input.userId).eq('product_id',input.productId).eq('source_type',input.sourceType).eq('source_url',input.sourceUrl).maybeSingle();if(findError)throw findError;if(existing)return mapAsset(existing); }
    const {data,error}=await this.db.from('product_media_assets').insert({user_id:input.userId,product_id:input.productId,source_type:input.sourceType,source_reference_id:input.sourceReferenceId??null,source_url:input.sourceUrl??null,mime_type:input.suppliedMimeType??null,analysis_status:'pending'}).select('*').single();if(error)throw error;
    await this.db.from('products').update({media_status:'pending',updated_at:new Date().toISOString()}).eq('id',input.productId).eq('user_id',input.userId);
    await this.recordEvent(input.userId,'product.media.asset.created',{product_id:input.productId,asset_id:data.id,source_type:input.sourceType});return mapAsset(data);
  }
  async claimNext(workerId:string,staleBefore:string):Promise<ClaimedProductMedia|null>{const {data,error}=await this.db.rpc('claim_next_product_media',{p_worker_id:workerId,p_stale_before:staleBefore});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)return null;const {data:product,error:productError}=await this.db.from('products').select('id,user_id,title,category').eq('id',row.product_id).eq('user_id',row.user_id).single();if(productError)throw productError;await this.db.from('products').update({media_status:'analyzing',updated_at:new Date().toISOString()}).eq('id',row.product_id).eq('user_id',row.user_id);return{asset:mapAsset(row),product:{id:product.id,userId:product.user_id,title:product.title,category:product.category??null},workerId};}
  async attachStoredFile(claim:ClaimedProductMedia,stored:StoredImage):Promise<ProductMediaAsset>{const {data:existing,error:findError}=await this.db.from('product_media_assets').select('*').eq('user_id',claim.asset.userId).eq('product_id',claim.asset.productId).eq('content_hash',stored.contentHash).neq('id',claim.asset.id).maybeSingle();if(findError)throw findError;if(existing){await this.db.from('product_media_assets').delete().eq('id',claim.asset.id).eq('user_id',claim.asset.userId).eq('processing_worker_id',claim.workerId);return mapAsset(existing);}const {data,error}=await this.db.from('product_media_assets').update({storage_path:stored.storagePath,mime_type:stored.mimeType,file_size:stored.fileSize,width:stored.width,height:stored.height,content_hash:stored.contentHash,updated_at:new Date().toISOString()}).eq('id',claim.asset.id).eq('user_id',claim.asset.userId).eq('processing_worker_id',claim.workerId).select('*').single();if(error)throw error;return mapAsset(data);}
  async completeAnalysis(claim:ClaimedProductMedia,analysis:ProductMediaAnalysis,qualityScore:number,needsReview:boolean):Promise<void>{const selection=needsReview?'rejected':'candidate';const {error}=await this.db.from('product_media_assets').update({classification:analysis.classification,has_text_overlay:analysis.hasTextOverlay,has_detected_branding:analysis.hasDetectedBranding,has_qr_code:analysis.hasQrCode,has_watermark:analysis.hasWatermark,possible_conflicting_commercial_text:analysis.possibleConflictingCommercialText,product_match_confidence:analysis.productMatchConfidence,quality_score:qualityScore,analysis_status:'completed',selection_status:selection,processing_started_at:null,processing_worker_id:null,last_error_code:null,analyzed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',claim.asset.id).eq('user_id',claim.asset.userId).eq('processing_worker_id',claim.workerId);if(error)throw error;if(needsReview){await this.db.from('products').update({media_status:'needs_review',updated_at:new Date().toISOString()}).eq('id',claim.asset.productId).eq('user_id',claim.asset.userId);await this.recordEvent(claim.asset.userId,'product.media.needs_review',{product_id:claim.asset.productId,asset_id:claim.asset.id,classification:analysis.classification});}else await this.db.from('products').update({media_status:'available',updated_at:new Date().toISOString()}).eq('id',claim.asset.productId).eq('user_id',claim.asset.userId).neq('media_status','selected');}
  async fail(claim:ClaimedProductMedia,errorCode:string,retryAt:string|null):Promise<void>{const terminal=!retryAt;const {error}=await this.db.from('product_media_assets').update({analysis_status:terminal?'failed':'pending',next_attempt_at:retryAt??new Date().toISOString(),processing_started_at:null,processing_worker_id:null,last_error_code:errorCode,updated_at:new Date().toISOString()}).eq('id',claim.asset.id).eq('user_id',claim.asset.userId).eq('processing_worker_id',claim.workerId);if(error)throw error;if(terminal)await this.db.from('products').update({media_status:'failed',updated_at:new Date().toISOString()}).eq('id',claim.asset.productId).eq('user_id',claim.asset.userId).neq('media_status','selected');}
  async listAssets(userId:string,productId:string):Promise<ProductMediaAsset[]>{const {data,error}=await this.db.from('product_media_assets').select('*').eq('user_id',userId).eq('product_id',productId).order('is_primary',{ascending:false}).order('quality_score',{ascending:false});if(error)throw error;return(data??[]).map(mapAsset);}
  async selectPrimary(userId:string,productId:string,assetId:string,selection:'auto_selected'|'manual_selected'):Promise<boolean>{const {data:asset,error:findError}=await this.db.from('product_media_assets').select('id,analysis_status,storage_path').eq('id',assetId).eq('product_id',productId).eq('user_id',userId).maybeSingle();if(findError)throw findError;if(!asset||asset.analysis_status!=='completed'||!asset.storage_path)return false;const {data:manual}=await this.db.from('product_media_assets').select('id').eq('user_id',userId).eq('product_id',productId).eq('selection_status','manual_selected').maybeSingle();if(selection==='auto_selected'&&manual)return false;await this.db.from('product_media_assets').update({is_primary:false,selection_status:'candidate',updated_at:new Date().toISOString()}).eq('user_id',userId).eq('product_id',productId).eq('is_primary',true);const {error}=await this.db.from('product_media_assets').update({is_primary:true,selection_status:selection,updated_at:new Date().toISOString()}).eq('id',assetId).eq('user_id',userId).eq('product_id',productId);if(error)throw error;await this.db.from('products').update({primary_media_asset_id:assetId,media_status:'selected',updated_at:new Date().toISOString()}).eq('id',productId).eq('user_id',userId);return true;}
  async markUnavailable(userId:string,productId:string):Promise<void>{const {count}=await this.db.from('product_media_assets').select('id',{count:'exact',head:true}).eq('user_id',userId).eq('product_id',productId);if(!count)await this.db.from('products').update({media_status:'unavailable',updated_at:new Date().toISOString()}).eq('id',productId).eq('user_id',userId);}
  async getPreferences(userId:string):Promise<ProductMediaPreferences>{const {data,error}=await this.db.from('media_preferences').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;return{preferNoText:data?.prefer_no_text??true,preferWhiteBackground:data?.prefer_white_background??false,preferLifestyleForClothing:data?.prefer_lifestyle_for_clothing??false,avoidPackaging:data?.avoid_packaging??true,naturalLanguage:data?.natural_language??null};}
  async recordEvent(userId:string,eventType:string,payload:Record<string,unknown>):Promise<void>{const {error}=await this.db.from('system_events').insert({user_id:userId,event_type:eventType,payload});if(error)throw error;}
  async discoverPendingWhatsApp(){const {data,error}=await this.db.from('products').select('id,user_id,source_reference_id').eq('source_type','whatsapp').in('media_status',['pending','failed']);if(error)throw error;const results:Array<ProductMediaCandidateInput&{connectionId:string;externalGroupId:string;externalMessageId:string}>=[];for(const row of data??[]){const {count}=await this.db.from('product_media_assets').select('id',{count:'exact',head:true}).eq('user_id',row.user_id).eq('product_id',row.id).eq('source_type','whatsapp');if(count)continue;const {data:analysis}=await this.db.from('promotion_analyses').select('captured_message_id').eq('id',row.source_reference_id).eq('user_id',row.user_id).maybeSingle();if(!analysis)continue;const {data:capture}=await this.db.from('captured_messages').select('external_message_id,external_group_id,media_metadata').eq('id',analysis.captured_message_id).eq('user_id',row.user_id).maybeSingle();if(!capture?.media_metadata?.available||!capture.external_message_id||!capture.external_group_id){await this.markUnavailable(row.user_id,row.id);continue;}const {data:source}=await this.db.from('captured_message_sources').select('connection_id').eq('captured_message_id',analysis.captured_message_id).eq('user_id',row.user_id).limit(1).maybeSingle();if(source?.connection_id)results.push({userId:row.user_id,productId:row.id,sourceType:'whatsapp',sourceReferenceId:analysis.captured_message_id,connectionId:source.connection_id,externalGroupId:capture.external_group_id,externalMessageId:capture.external_message_id});}return results;}
}
